controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    prefix: /api
    type: attribute

api_login_check:
    path: /api/login_check